# Generated by Django 5.2.6 on 2025-09-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='nivel',
            field=models.CharField(choices=[('GRAVE', 'Grave'), ('ALTA', 'Alta'), ('MEDIA', 'Media')], default='MEDIA', max_length=5),
        ),
    ]
