# Generated by Django 5.2.4 on 2025-09-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_alerta_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='dispositivos/'),
        ),
    ]
