# Generated by Django 5.2.4 on 2025-10-08 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_dispositivo_imagen'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zonas_dispositivo', to='organizations.organization'),
        ),
    ]
