# Generated by Django 5.2.5 on 2025-11-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='tipo_producto',
            field=models.CharField(choices=[('Liquido', 'Líquido'), ('Seco', 'Seco')], default='Liquido', max_length=10),
        ),
    ]
