# Generated by Django 5.2.5 on 2025-11-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_remove_producto_categoria_alter_producto_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_producto',
            field=models.CharField(choices=[('Liquido', 'Liquido'), ('Seco', 'Seco')], default='Liquido', max_length=10),
        ),
    ]
