# Generated by Django 5.2.5 on 2025-11-03 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_alter_proveedor_tipo_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desempeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calidad', models.IntegerField(default=0)),
                ('entrega', models.IntegerField(default=0)),
                ('precio', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenos', to='proveedores.proveedor')),
            ],
        ),
    ]
