# Generated by Django 5.2.5 on 2025-11-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_desempeno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='tipo_producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('Liquido', 'Liquido'), ('Seco', 'Seco')], default='Liquido', max_length=10),
        ),
    ]
