# Generated by Django 5.2.5 on 2025-11-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0009_remove_proveedor_tipo_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('Liquido', 'Líquido'), ('Seco', 'Seco')], max_length=50),
        ),
    ]
